### ISSUE TITLE
Some assets don't load correctly due to non-relative paths

### ISSUE THREAD

**Issue by rmars** [runconduit/conduit#1019]
If you navigate directly to a particular namespace's page, (e.g. pasting `http://localhost:8084/namespaces/conduit` in the browser and hitting enter) you'll get several asset 404s in the web console, and any icons we use will show up as unfilled boxes.

Some of this was fixed in #959 (rather hackily, by adding a contingency check for the sidebar image) but the icons on the page still show up as boxes. The sidebar icons load correctly however.

Options for fixing this:
- fixing the loading path for these assets
- replacing the fontawesome icons with an html or unicode symbol
- ???

Example:
![screen shot 2018-05-25 at 12 05 56 pm](https://user-images.githubusercontent.com/549258/40561948-0647f054-6014-11e8-92a5-afca941c5f61.png)

**Comment by grampelberg** [comment]
- Because the assets are being loaded via. CSS (which is at build time), our URLs can have multiple depths (see /namespaces/*) and everything is relative, this isn't something webpack will be able to solve for us without more work than it is probably worth.
- Replace the http router that web is using, with something that has more fuzzy matching. There would be a route for assets `*/assets/*` and for everything else `/namespaces`. 
- Move the assets to a separate domain and load them from there.
- Switch to using something other than font-awesome (which'd allow us to do direct imports and place into the jsx).

I'm not sure any of these are particularly good options. What does everyone think?

**Comment by rmars** [comment]
Yeah, to your first point, could we use something like `string-replace-loader` for our css and modify the paths? It'd probably for now also just replace `/namespace/` but we don't have many urls, so hardcoding the url replacements could work.

Hm, probably the least yucky would be using something that would let us do direct imports.
The problem is the `font-awesome.min.css` file which uses a relative path.

I'd support the simplest solution here.
