### ISSUE TITLE
Reduce the time it takes for UI to reflect state of pods and deployments

### ISSUE THREAD

**Issue by dadjeibaah** [runconduit/conduit#219]
There is a little bit of delay between running pods and the time they turn green in the web UI. We may need to fiddle with the refresh rates to figure out what would be appropriate.

![pod-status](https://user-images.githubusercontent.com/2197104/35465648-6c4545ce-02b2-11e8-9bbf-5c90df87583a.gif)

**Comment by briansmith** [comment]
One option would be to have the dots turn green immediate if/when the proxy first connects to the controller. That is, don't wait for the proxy to send/receive traffic telemetry, but initially just accept a (any) positive signal of health from the proxy to get it green.

**Comment by rmars** [comment]
There have been updates to this page since January:
- we now refresh this page every 2 seconds
- the count of meshed pods is now based on whether the pod has the `conduit.io/proxy-version` annotation, so a pod will show up as meshed as soon as it's injected, rather than when we receive telemetry from it

I think these should get rid of the lag. We can reopen this if that is not the case.
