### ISSUE TITLE
`$ conduit version` shows "unknown" for client version for a local/testing build

### ISSUE THREAD

**Issue by pcalcado** [runconduit/conduit#223]
Running `$ conduit version` has the following flow:
```shell
pcalcado@arbeitsziege.local:/Users/pcalcado/code/src/github.com/runconduit/conduit  git:(master) $ git pull --rebase origin master
From github.com:runconduit/conduit
[...]
Current branch master is up to date.
pcalcado@arbeitsziege.local:$ rm `which conduit` ; go build -o $GOPATH/bin/conduit ./cli
pcalcado@arbeitsziege.local:$ conduit version
Client version: unknown
Server version: testing
```

The expected output would be
```shell
Client version: testing
Server version: testing
```

**Comment by klingerf** [comment]
This behavior is a result of my changes in #208. Specifically, we no longer hardcode the stable version in the go codebase. Instead, the version is set to "unknown" by default, and it's overridden via go's `ldflags` to set the version automatically based on the build environment. As part of that change I've updated all of our docker builds to set `ldflags`, so that any binary produced via docker has the correct version.

I agree that seeing "unknown" in the version output is confusing. Here are a few possible improvements:

* Change the default version string to something more meaningful (maybe "dev" or "local"), [here](https://github.com/runconduit/conduit/blob/master/pkg/version/version.go#L13).

* Add better documentation to encourage the use of `ldflags` outside of docker builds. For instance:

```
$ go run -ldflags="-X github.com/runconduit/conduit/pkg/version.Version=aWeSoMe" cli/main.go version
Client version: aWeSoMe
Server version: unavailable
```

* Modify the `bin/go-run` script to set `ldflags` when building binaries, and encourage users to use that script when running locally.

Happy to tackle any of these, if you think that would help to clarify.

---

I think there's also some confusion about the "correct" way to produce a conduit binary, given the new version override setup. The recommended workflow for local development is described in BUILD.md, [here](https://github.com/runconduit/conduit/blob/master/BUILD.md#comprehensive). Specifically, the `bin/conduit` script will execute static binaries from the `target/cli` directory, and it will build those binaries using the `bin/docker-build-cli-bin` script, if they don't already exist.

So the most reliable way to produce a properly versioned conduit binary from a local branch is to use the `bin/docker-build-cli-bin` script. That script is a bit slow, however, since it produces binaries for all supported architectures. An alternative, if you just want to build locally and install on top of your existing conduit installation, would be to do something like:

```
$ which conduit
/Users/kl/.conduit/bin/conduit

$ conduit version
Client version: v0.1.3
Server version: unavailable

$ go build -o `which conduit` -ldflags="-X github.com/runconduit/conduit/pkg/version.Version=testing" ./cli

$ conduit version
Client version: testing
Server version: unavailable
```

**Comment by pcalcado** [comment]
@klingerf sorry I am late here but re: #284, I am not sure about `latest`. The Docker jargon has created an expectation that `latest` isn't really a version number, but a label _manually_ applied to the latest available version.

I think that a solution for #223 would be to make sure that for all common use cases (not limited to Conduit users but also testing and developer workflow) there is always a version set, usually like `git-5b53123e`. The fallback to the hardcoded version should only happen when something goes wrong, and in this case I think that returning `undefined` would be ok (`unknown` makes me think that the system tried to fetch the version and failed).

Re-opening to discuss.

**Comment by klingerf** [comment]
@pcalcado Apologies for my delay too. Per your suggestion, I'll switch the default version string to `undefined`, and I'll update our run scripts to set the version when compiling the code.
