### ISSUE TITLE
Support Hashicorp Nomad

### ISSUE THREAD

**Issue by leowmjw** [runconduit/conduit#30]
I am interested in using Conduit with Nomad instead of Kubernetes; I would be interested in taking a stab at a port if the changes involve modifying the Golang part of the code (total Rust noob here).  

Are there plans to make Conduit not so tightly coupled with Kubernetes?  If so, which part of the code base would you suggest I start with.  Any pointers appreciated :)

Thanks!

**Comment by anubhavmishra** [comment]
May be look at [linkerd](https://linkerd.io/config/1.3.4/linkerd/index.html#consul-service-discovery)? It already has a really nice namerd integration out of the box.

**Comment by olix0r** [comment]
Hi @leowmjw! Sorry I didn't see this sooner.

We currently don't have plans to make Conduit generic across environments -- the Kubernetes API gives us a lot of functionality that we want to build _into_, rather than try to build an abstraction across arbitrary environments.  Once we've hit 1.0 stability- and feature-completeness, we may be able to consider how we can address other use cases.

As @anubhavmishra points out, Linkerd is probably our best recommendation for Nomad environments at this point.
