### ISSUE TITLE
Distribute Conduit CA bundle via a configmap in every namespace where a conduit proxy is installed

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#309]
`conduit install` creates a `conduit.ca-bundle-distributor` pod. Upon startup, and whenever it sees the `conduit.conduit-ca-bundle` ConfigMap updated and/or whenever it sees a new pod containing a conduit proxy created, it copies the contents of that configmap to `<namespace>.conduit-ca-bundle`, for each namespace that has at least one conduit proxy.

I have made a prototype of this that, upon startup, copies the configmap to every namespace. It doesn't do the filtering to limit it to only namespaces that have a conduit proxy installed, it doesn't watch for updates to the configmap, and it doesn't handle the case where the namespace already has an old version of the configmap. However, it does demonstrate the RBAC-related stuff that we will need.

**Comment by briansmith** [comment]
It was asked why we need to copy the ConfigMap into every namespace that has a Conduit-proxied service, instead of just mounting a single one that lives in the `conduit` namespace from every pod.

According to the k8s docs at https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/:

> ConfigMaps reside in a specific namespace. A ConfigMap can only be referenced by pods residing in the same namespace.

**Comment by klingerf** [comment]
Am going to start implementing this soon, but wanted to discuss a different potential approach:

Rather than having a centralized process that pushes a configmap to every namespace where a conduit proxy is running, what if we create just one configmap in the conduit namespace, and then inject a watcher container alongside each proxy container? The watcher container could watch the configmap from the conduit namespace and write its contents to an [emptyDir volume mount](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir), which would also be mounted by the proxy container.

I think that the main flaw with this approach is that the watcher container would not have the right RBAC privileges to read the configmap, and since we're injecting the watcher we can't change its service account. But I wanted to at least throw it out there in case there were any other workarounds that might be possible. I'm a bit nervous about introducing a conduit controller process with the privileges to modify all config maps in all namespaces in a user's cluster.

**Comment by briansmith** [comment]
> just one configmap in the conduit namespace, and then inject a watcher container alongside each proxy container?

In that approach, I think the proxy could just do the watching. It would be weird to have two sidecars, especially since the proxy is supposed to be "ultra-lightweight."

> I think that the main flaw with this approach is that the watcher container would not have the right RBAC privileges to read the configmap, and since we're injecting the watcher we can't change its service account. 

That's right.

Also, in that approach, every pod would need to maintain a connection to the Kubernetes API server AND the conduit control plane. Every node already maintains a connection to the Kubernetes API server via the kubelet, and the idea of copying the configmap and mounting it directly in each pod is to make use of that.

> I'm a bit nervous about introducing a conduit controller process with the privileges to modify all config maps in all namespaces in a user's cluster.

The RBAC role binding mechanism can take a name of the object to which the permission is being applied. I am hoping that we can restrict the permission of the role binding to only objects named "conduit-ca" in each namespace.

Note that the initial plan is to have the CA create the secrets for each pod's private key + certificate, one secret per pod, and *that* will be actually be more risky than "write any configmap" because it will be a "write any secret" permission. (This will be revisited once we've got everything bootstrapped.)

**Comment by olix0r** [comment]
> In that approach, I think the proxy could just do the watching. It would be weird to have two sidecars, especially since the proxy is supposed to be "ultra-lightweight."

i don't disagree, but this would be a tighter coupling with the proxy and the k8s api, which is something we more generally hope to avoid

**Comment by briansmith** [comment]
> > In that approach, I think the proxy could just do the watching. It would be weird to have two sidecars, especially since the proxy is supposed to be "ultra-lightweight."
> 
> i don't disagree, but this would be a tighter coupling with the proxy and the k8s api, which is something we more generally hope to avoid

Whether something is split into two processes/containers or one process/container doesn't really change this much as long as the pieces are kept segregated.

Keeping the proxy more independent of Kubernetes is also a benefit of the configmap-based mechanism. There should be no (new) Kubernetes-specific code in the proxy at all.

**Comment by klingerf** [comment]
Thanks for the feedback -- that all makes sense.

Fwiw, I came up with a semi-viable workaround for this issue:

> the watcher container would not have the right RBAC privileges to read the configmap

Instead of storing the certificate in a configmap, we could create a custom resource (e.g. `certificates.conduit.io`), and then grant all service accounts permission to watch that custom resource only, without modifying their permissions with regard to existing kubernetes resources. That would be substantially better than granting all accounts the ability to read the configmap from the conduit namespace.

But I agree that running an additional sidecar is not ideal, and having every pod maintain a connection to the Kubernetes API is also problematic.

**Comment by klingerf** [comment]
I had a follow-up question related to the original approach described here:

> whenever [the distributor pod] sees a new pod containing a conduit proxy created, it copies the contents of that configmap to `<namespace>.conduit-ca-bundle`, for each namespace that has at least one conduit proxy.

Does this mean that the first injected pod in each namespace will fail to start until the distributor pod in the conduit namespace has identified that the pod exists and creates the configmap?

Testing locally, it looks like the pod stays in the `Init` state until the configmap has been created, and there's a backoff on checking for the existence of the configmap.

```
$ kubectl get po
NAME                      READY     STATUS     RESTARTS   AGE
kltest-7cd6c84874-6ltkv   0/2       Init:0/1   0          3s
```

```
$ kubectl describe po kltest-7cd6c84874-6ltkv
...
  Warning  FailedMount            6s (x5 over 14s)  kubelet, minikube  MountVolume.SetUp failed for volume "conduit-ca-bundle" : configmaps "conduit-ca-bundle" not found
```

The pod does eventually start after the configmap is created, but with the backoff it seems like we could be introducing some nontrivial latency here. Or worst case, if the distributor process stops running, then users would no longer be able to deploy injected pods to new namespaces.

**Comment by briansmith** [comment]
> The pod does eventually start after the configmap is created, but with the backoff it seems like we could be introducing some nontrivial latency here. Or worst case, if the distributor process stops running, then users would no longer be able to deploy injected pods to new namespaces.

When mounting the configmap, there is an option to mount it as "optional" which will allow the proxy to start even if the configmap isn't present. Then the proxy can implement its own mechanism for lazily loading the configmap.

**Comment by klingerf** [comment]
> When mounting the configmap, there is an option to mount it as "optional" which will allow the proxy to start even if the configmap isn't present.

Ok great, have tested this locally and it works as expected.
