### ISSUE TITLE
Add Prometheus recording rules to telemetry pipeline

### ISSUE THREAD

**Issue by siggy** [runconduit/conduit#336]
## Problem

Our Prometheus queries are not as fast as they could be. The performance results documented in #298 demonstrate that some queries continue to take several seconds, notably those involving `histogram_quantile` and `response_latency_ms`. These queries are slow because they require significant computation at read-time.

## Proposal

[Prometheus recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) allow write-time computation of metrics, making reads faster.

We can implement recording rules by specifying a rules file, probably where we specify a Prometheus config file, and then reference the rules file via `rule_files` in that config:
https://github.com/runconduit/conduit/blob/b691c2e25bc060ae315d8b990c237811b8e5b91f/cli/cmd/install.go#L373

Here are a couple examples of slow queries that are candidates for recording rules:

```
# p50/p95/p99 histogram latency
histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{}[30s])) by (target_deployment,le))

# query volume over time
sum(irate(responses_total{}[30s])) by (target_deployment))
```

#### Rules for dynamic label values

Some Prometheus queries are not known until runtime, as they contain information in the telemetry data. For example:

```
histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{target_deployment="emojivoto/emoji"}[30s])) by (source_deployment,le,target_deployment))

sum(irate(responses_total{target_deployment="emojivoto/emoji"}[30s])) by (target_deployment,classification,target_deployment)
# (this previous query came from our conduit logs, the repeated `target_deployment` seems unnecessary, investigate this).
```

Investigate the feasibility of recording rules that handle these types of queries with dynamic labels. The `level:metric:operations` examples may be of some use here: https://prometheus.io/docs/practices/rules/#naming-and-aggregation

#### rules reloading

Possibly related to the managing queries with dynamic values, Prometheus supports dynamic reloading of recording rules. If our recording rules must be modified at runtime, we could build a process that updates the recording rules `ConfigMap`, and then sends a `SIGHUP` to the Prometheus process.

## Relevant links
- https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/
- https://prometheus.io/docs/practices/rules/

**Comment by hawkw** [comment]
I've got a branch that changes Conduit to use recording rules for the histogram quantile queries. However, after doing some fairly intense stress testing, we've noted that:
1. Query latency on the current master is _much_ better than it was in the performance results mentioned in #298; I suspect some of the commits since that branch was merged have had a pretty big impact,
2. After running Conduit builds with and without recording rules in GKE overnight, the build with recording rules actually exhibits _higher_ prometheus/telemetry latencies than the current master, sometimes significantly so. The prometheus query latency with recording rules appears to be about 200ms greater, while the prometheus/telemetry latency reported by the Go telemetry server is sometimes much greater.
3. Both master and my recording rules branch exhibit pretty similar performance in Minikube: after running for about 30 minutes, page loads will occasionally display the loading spinner, but rarely for longer than a second. There are occasionally major lag spikes during which page load time is significantly increased, but this effects the entire host system and it doesn't seem like there's much that Conduit can do about it.

I'm quite unsure why querying the metric generated by a recording rule actually appears to be slower than just running that query, most of the time --- this goes totally counter to my expectations. This could warrant further investigation.

However, since we're not really seeing a huge impact from query latencies on the current master, @adleong and I have decided to close this ticket for now. We could continue investigating recording rules if query latency becomes a problem again in the future.
