### ISSUE TITLE
Proxy does not handle empty request bodies correctly (except for HEAD and GET?)

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#447]
This is a follow-up to #402 to track the real solution to the problem that the proxy doesn't handle requests without a body correctly. The PR for #402 only partially resolves the issue. Really we should fix the real issue. I very vaguely understand that to require some changes to the Hyper API or some other more drastic solution.

In particular, DELETE will almost never have a request body, so many REST APis would be affected by this.

/cc @olix0r @seanmonstar

**Comment by seanmonstar** [comment]
The bug here is a combination of a few things:

- hyper's Request holds an optional body. If not set, then no body is assumed. Otherwise, it assumes a body.
- The body is generic over a futures Stream, so there is no way to ask anything about it before the headers are written.
- If the body is set, and there is no content-length header, it inserts Transfer-Encoding chunked, since the length cannot be calculated.
- The proxy maps bodies from both hyper and h2, with the result that client requests always have the body set, even if internally the stream will be empty.

In the long term, hyper is going to change it's body type to a trait with more methods that it can ask about if the body is empty.

In the short term, I think a small addition in hyper to expose that server bodies are empty, and then a modification in the proxy to check that, can allow optionally setting the body in hyper client requests.
