### ISSUE TITLE
conduit check takes 90 seconds to detect a missing K8s cluster

### ISSUE THREAD

**Issue by wmorgan** [runconduit/conduit#553]
On Conduit 0.3.0, with minikube stopped, I get this behavior:

```
william:~$ time conduit check
kubectl: is in $PATH............................................................[ok]
kubectl: has compatible version.................................................[ok]
kubectl: can talk to Kubernetes cluster.........................................[FAIL]  -- Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout

kubernetes-api: can initialize the client.......................................[ok]
kubernetes-api: can query the Kubernetes API....................................[ERROR] -- HTTP GET request to endpoint [https://192.168.99.100:8443/api/v1/] resulted in error: [Get https://192.168.99.100:8443/api/v1/: dial tcp 192.168.99.100:8443: i/o timeout]

conduit-api: can retrieve status via gRPC.......................................[ERROR] -- Post https://192.168.99.100:8443/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/SelfCheck: dial tcp 192.168.99.100:8443: i/o timeout

Status check results are [ERROR]

real	1m30.386s
user	0m0.351s
sys	0m0.063s
```

`check` should detect this in <90 seconds

**Comment by franziskagoltz** [comment]
I’ve done some research on this and we’re not actually wrapping any connection attempts in retries or anything similar in our code for `conduit check`. 

One approach I’m thinking of, is using a timeout from the kubernetes API on`rest.Config` shipped with client-go (https://godoc.org/k8s.io/client-go/rest#Config). 
But I’m not sure we want to do that, since in case the user _is_ configured to connect to a cluster, we’d want to assure that we’re trying to connect and don’t timeout prematurely. 

I’ve also looked into getting the `kubectl cluster-info` but that is also timing out under the k8s-hood at about 90secs if minikube is stopped. 

Does anyone have any opinions on how to best approach this and reduce the time it takes`conduit check` to determine a missing k8s cluster?

**Comment by klingerf** [comment]
I think the issue is that the golang `http.Client` instance that the CLI uses to talk to the public API does not include a timeout. So we will wait indefinitely on all http requests. The client that we use for making requests is constructed here:

https://github.com/runconduit/conduit/blob/master/pkg/k8s/api.go#L43

If you added a `Timeout: 5 * time.Second` field to that struct, that would properly time out the API calls made by `conduit check`. But that approach will unfortunately break `conduit tap`, since adding a timeout to the http client used to issue the tap request will cause the tap command to timeout after 5 seconds, and we want it to run indefinitely.

In that case, rather than hardcoding a timeout into the client itself, we might want to consider using a request context with the check requests that applies the timeout. There's more info about that here:

https://golang.org/pkg/context/#WithTimeout

**Comment by ahume** [comment]
I wondered whether there could be a solution to this at the Client level by setting `DialContext.Timeout` on the `Transport`. This would limit the time establishing a TCP connection, and shouldn't effect `conduit tap`. I assume it's the default value of this that's timing out the three checks at 30s each. However, it wasn't clear to me whether the Transport provided by the k8s go-client can be configured to set this value?

I lieu of this I have a branch which applies the timeouts via request context which (depending on your view on the above) might be useful. I'll push a PR today in any case.
