### ISSUE TITLE
Proxy gets out of sync with Destination service on reconnects

### ISSUE THREAD

**Issue by briansmith** [runconduit/conduit#573]
In the services discovery logic in the proxy (control/discovery.rs), when the connection to the Destination service is broken (indicated by the stream ending), a reconnect is done. Once the reconnect has occurred the controller will send an `Add` message to the proxy giving the current set of endpoints for the service. The proxy merges this set of endpoints into the set it currently has. However, it never removes any entries that weren't in the set; they will stay in its set forever. (This is based purely on my reading of the code.)

Consider this timeline for a service example.namespace.svc.cluster.local:
1. The proxy subscribes to example.namespace.svc.cluster.local.
2. The Destination service responds with Add {1.2.3.4, 5.6.7.8}.
3. The proxy gets disconnected. It will use {1.2.3.4, 5.6.7.8} as the set of destinations indefinitely.
4. The endpoint 1.2.3.4 is removed, e.g. the pod is de-scheduled.
5. The proxy re-subscribes to example.namespace.svc.cluster.local.
6. The Destination service responds with Add {5.6.7.8}
7. The proxy merges {5.6.7.8} into {1.2.3.4, 5.6.7.8}, resulting in {1.2.3.4, 5.6.7.8}.

At point 4 the Destination service is out of sync with Kubernetes since the proxy thinks 1.2.3.4 is a valid endpoint when Kubernetes knows it is not. At point 7 the destination service and the proxy would be out of sync since the proxy thinks 1.2.3.4 is a valid endpoint and the Destination service knows it is not.

One possible solution would be to clear the set of endpoints for a service when we detect that we need to reconnect to the Destination service. However, this would mean that service discovery would completely fail whenever the connection to the Destination service fails, which is bad for uptime.

A better solution would be to clear the set of endpoints for a service when we receive the first message (e.g. Add or NoEndpoints/Reset) from the Destination service after reconnecting, and then process the message. I think @olix0r has some reservations about doing this.

A more elaborate solution would be to have a TTL associated with all entries, and start expiring entries as soon as we disconnect from the Destination service and/or as soon as we reconnect from the Destination, depending on what we want to prioritize.

This is relevant to #155 because a DNS query and response is basically equivalent to connecting to the destination service, doing a single query, getting a single Add message, disconnecting, and then scheduling a reconnect.

We need to decide:
1. When we are disconnected from the destination service, should we expire and remove entries? if so, how.
2. When we reconnect to the destination service and receive a Reset{service_exists=true} message or an Add message, should we immediately remove the old entries from the previous connection, or should we expire them by TTL?

**Comment by seanmonstar** [comment]
Couldn't we just on reconnect, treat that special, where once we get the first message, diff with out current set, and everything we didn't get an `Add` for, we assume we would have received a `Remove` if we weren't disconnected, and so remove at that stage. By waiting for after the diff, we don't have to tear down any services that would never have been removed.

**Comment by briansmith** [comment]
> Couldn't we just on reconnect, treat that special, where once we get the first message, diff with out current set, and everything we didn't get an Add for, we assume we would have received a Remove if we weren't disconnected, and so remove at that stage. By waiting for after the diff, we don't have to tear down any services that would never have been removed.

That's what I'd like to do initially.

What if we're disconnected for a long time? How long do we want to keep using stale service discovery information while disconnected?

**Comment by adleong** [comment]
When I implemented the discovery service, I intended for service discovery state to be local to each gRPC stream.  That means that the first message on each stream should be an ADD with a comprehensive list of addresses and any address set from a previous stream should be entirely replaced.  This is probably the behavior we should implement for now.

There are larger questions of resiliency that we'll want to look at going forward.  I like to think of the available set of addresses to be influenced by 3 things: _Service Discovery_, _Connectivity_, and _Health_.  _Service Discovery_ is the information returned from the SD source (the destination service in this case), _Connectivity_ is whether the proxy can establish a connection to the address, and _Health_ can be either an active (out-of-band) measure of health where we poll some kind of health endpoint on the destination to determine if it is healthy or a passive (in-band) measure of health were we examine live responses to determine if it is healthy.  

The primary goal of this is to be resilient to service discovery failures where the service discovery backend returns incorrect (or empty!) data.  For example, in Finagle, when an address is removed from service discovery, that address will remain in the load balancer until that address becomes disconnected or unhealthy.  This feature, called `probation`, can be problematic in scheduled environments where IP addresses can be reused because if an IP is re-assigned from one service to another then the proxy can't rely on a connectivity failure to corroborate the service discovery removal.

Thinking about it this way suggests that TTLs may not be a good approach for when the proxy is disconnected from the destination service for long periods of time.  The last known information from the discovery service is the best information the proxy has about the state of service discovery and shouldn't be expired unless better information is available.  Of course, connectivity and health should be layered onto this data so that we stop sending to addresses that are unreachable or unhealthy.

**Comment by briansmith** [comment]
> For example, in Finagle, when an address is removed from service discovery, that address will remain in the load balancer until that address becomes disconnected or unhealthy. This feature, called probation, can be problematic in scheduled environments where IP addresses can be reused because if an IP is re-assigned from one service to another then the proxy can't rely on a connectivity failure to corroborate the service discovery removal.

I am not sure we should do this probation thing by default. AFAICT removal from service discovery is the only way Kubernetes has to tell us to gracefully stop sending traffic to a pod. Some endpoints might have been removed from service discovery but remain available until traffic has ceased before the pods (most likely, a deployment describing the pods) is deleted. Especially since we don't have retry logic yet to cope with the case where the administrator has decided to delete or roll the deployment even though we'd be sending traffic to it.

In other words, if Kuberentes (or DNS or whatever) actively tells us that a service has been removed, then in the absence of other functionality to cope with that, we should stop sending traffic to it.

> Thinking about it this way suggests that TTLs may not be a good approach for when the proxy is disconnected from the destination service for long periods of time. The last known information from the discovery service is the best information the proxy has about the state of service discovery and shouldn't be expired unless better information is available.

I think, in the disconnected state, it is OK to use the stale information until we get better information. Anyway we don't have a better idea now.

> Of course, connectivity and health should be layered onto this data so that we stop sending to addresses that are unreachable or unhealthy.

Agreed.

In summary, here's what I'm planning to implement:
1. Update the new Destination API `Reset` message's semantics to indicate that `Reset { service_exists: true }` should not be sent unless there are no endpoints available at all. This way
2. Update the proxy's reception of `Add` messages so that the first `Add` received after a reconnect replaces the current set of endpoints, instead of adding to them. 
3. Update the documentation for `Add` messages to indicate that the server should, especially for the first `Add` message prefer to send multiple addresses in the message.
4. Continue to use stale discovered information until we receive the first Add during a reconnect.
