### ISSUE TITLE
proxy can error due to HTTP/2 stream resets

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#754]
As described in https://github.com/carllerche/h2/issues/256, it's possible for some stream resets to cause `h2` to panic. This is very likely to impact the proxy. @carllerche @seanmonstar

**Comment by seeekr** [comment]
I'm seeing something like this:

`conduit_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500`

when I just terminate my HTTP server that conduit is proxying for, while processing a response and not having written anything to it yet.

Is this related? Sounds like it could be. Or should I file a separate issue for that?

**Comment by seanmonstar** [comment]
@seeekr no, that would be different. A panic in the proxy will in most cases make it crash, not report a 500 error.

As to your issue... you're killing an HTTP server mid-response? Seems like the proxy seeing that and returning 500 is correct.

**Comment by seeekr** [comment]
Thanks @seanmonstar. If that's what it's doing then that is acceptable behavior. Just wasn't sure if this indicated a problem on conduit's part which I should look into understanding, since I was overall seeing some weird behavior in terms of connectivity for my service. (Killing it mid-response was not great, of course, and I've since changed that to be a little more graceful.)

Keep up the good work! 👍

**Comment by olix0r** [comment]
https://github.com/carllerche/h2/pull/258 will fix this. We learned that the conduit proxy will _not_ panic in these situations, as it is built in release-mode. Panics are limited to debug builds.

**Comment by siggy** [comment]
Fixed in https://github.com/carllerche/h2/pull/258. @olix0r please re-open if this is still an issue.

**Comment by carllerche** [comment]
I would leave this open for now. There still is one known issue. Relates to https://github.com/carllerche/h2/pull/261 and https://github.com/carllerche/h2/pull/259.

**Comment by carllerche** [comment]
I have squashed many bugs. There is still some work I would like to get done, then I will release a new crate.

Please ping me if this is not closed by next release.

**Comment by olix0r** [comment]
h2-0.1.7 [fixes](https://github.com/runconduit/conduit/commit/d24a3410d8db03af3616cadc3eda1b60ad986cfc) a whole slew of state management corner-cases
